<?php declare(strict_types=1);

namespace NZTim\Ipbl;

use Illuminate\Http\Request;
use NZTim\Geolocate\Geolocate;

class Ipbl
{
    private EntryRepo $entryRepo;
    private Geolocate $geo;

    public function __construct(EntryRepo $entryRepo, Geolocate $geo)
    {
        $this->entryRepo = $entryRepo;
        $this->geo = $geo;
    }

    public function add(string $ip, int $severity, string $reason): void
    {
        $country = $this->geo->fromIp($ip);
        $this->entryRepo->add($ip, $country, $severity);
        log_info('ipbl', "{$ip} | {$country} | {$severity} | {$reason} ");
    }

    public function evaluate404(Request $request, int $severity = 5): void
    {
        $path = $request->path();
        if ($this->badPath($path)) {
            $this->add($request->ip(), $severity, "Bad 404: {$path}");
        }
    }

    private function badPath(string $path): bool
    {
        $paths = [
            '.env',
            '.env.backup',
            '/wp/wp-includes/wlwmanifest.xml',
            '/xmlrpc.php',
            '0.php',
            '02.php',
            '031.php',
            '1.php',
            '10.php',
            '11.php',
            '12.php',
            '123.php',
            '2.php',
            '222.php',
            '3.php',
            '333.php',
            '406.php',
            '444.php',
            '5.php',
            '7.php',
            'Properties/launchSettings.json',
            '_profiler/phpinfo',
            '_profiler/phpinfo.php',
            'admin-app/.env',
            'admin.php',
            'admin.zip',
            'admin/.env',
            'administrator.env',
            'administrator.zip',
            'angular.json',
            'api/.env',
            'api/config/tsconfig.json',
            'app/.env',
            'app/config/.env',
            'app/etc/config.local.php',
            'app/etc/config.php',
            'app/etc/env.local.php',
            'app/etc/env.php',
            'app_dev.php/_profiler/phpinfo',
            'application/.env',
            'application/config/autoload.php',
            'application/config/config.php',
            'application/config/constants.php',
            'application/config/database.php',
            'application/config/doctypes.php',
            'application/config/email.php',
            'application/config/encryption.php',
            'application/config/foreign_chars.php',
            'application/config/hooks.php',
            'application/config/migration.php',
            'application/config/mimes.php',
            'application/config/profiler.php',
            'application/config/routes.php',
            'apps/.env',
            'appsettings.Development.json',
            'appsettings.Local.json',
            'appsettings.Production.json',
            'appsettings.QA.json',
            'appsettings.Staging.json',
            'appsettings.Test.json',
            'appsettings.json',
            'asdf.php',
            'assets/.env',
            'aws-secret.yaml',
            'aws.yml',
            'aws_credentials',
            'backend/.env',
            'backup.php',
            'backup.sql',
            'backup.zip',
            'backup/config.php',
            'backup2.php',
            'backups/.env',
            'base/.env',
            'beta/.env',
            'blog/.env',
            'blog/wp-login.php',
            'bundleconfig.json',
            'conf/.env',
            'conf/application.json',
            'config.js',
            'config.json',
            'config.php',
            'config/.env',
            'config/acl.config.php',
            'config/app.default.php',
            'config/app.php',
            'config/app_local.php',
            'config/application.config.php',
            'config/auth.php',
            'config/autoload/global.php',
            'config/autoload/local.php',
            'config/aws.json',
            'config/aws.yml',
            'config/aws_config.json',
            'config/aws_credentials.json',
            'config/bootstrap.php',
            'config/broadcasting.php',
            'config/cache.php',
            'config/cli_bootstrap.php',
            'config/config.json',
            'config/config.php',
            'config/daemon.json',
            'config/database.config.php',
            'config/database.php',
            'config/default.json',
            'config/dev.json',
            'config/development.config.php',
            'config/development.json',
            'config/env.php',
            'config/filesystems.php',
            'config/local.json',
            'config/mail.php',
            'config/module.config.php',
            'config/paths.php',
            'config/php.ini',
            'config/prod.json',
            'config/production.config.php',
            'config/production.json',
            'config/queue.php',
            'config/requirements.php',
            'config/routes.php',
            'config/security.config.php',
            'config/services.php',
            'config/session.php',
            'config/settings.json',
            'config/staging.json',
            'config/test.config.php',
            'config/test.json',
            'config/view.php',
            'core/.env',
            'core/app/.env',
            'crm/.env',
            'cron/.env',
            'dashboard/phpinfo.php',
            'database.zip',
            'dev/.env',
            'dev/phpinfo.php',
            'development/.env',
            'docker-compose.yml',
            'docker/.env',
            'docker/app/.env',
            'dump.sql',
            'env.backup',
            'front/.env',
            'frontend_dev.php/$',
            'helpers/utility.js',
            'hosting.json',
            'i.php',
            'index.php/phpinfo',
            'info.php',
            'infophp.php',
            'install/index.php',
            'keys/aws_keys.json',
            'kyc/.env',
            'lab/.env',
            'laravel/.env',
            'laravel/core/.env',
            'launchSettings.json',
            'lib/.env',
            'library/.env',
            'live_env',
            'local/.env',
            'login/index.php',
            'mailer/.env',
            'manifest.json',
            'meteor.settings.json',
            'new/.env',
            'new/.env.local',
            'new/.env.production',
            'old/.env',
            'old_phpinfo.php',
            'pass.php',
            'php-info.php',
            'php.php',
            'php_info.php',
            'phpinfo',
            'phpinfo.php',
            'phpinfo.php3',
            'phpinfo.php4',
            'phpinfo.php5',
            'phpinfos.php',
            'phpmyadmin',
            'phpversion.php',
            'pinfo.php',
            'prevlaravel/sftp-config.json',
            'private/config.json',
            'prod/.env',
            'public/.env',
            'public/client/planinfo',
            'saas/.env',
            'secrets.json',
            'secrets/aws.json',
            'secrets/aws_config',
            'secrets/aws_credentials',
            'secured/phpinfo.php',
            'settings.json',
            'sftp-config.json',
            'sftp.json',
            'shared/.env',
            'site/.env',
            'sitemaps/.env',
            'src/config/config.json',
            'src/settings.json',
            'storage/.env',
            'storage/aws.json',
            'storage/logs/laravel.log',
            'symfony/_profiler/phpinfo',
            'temp.php',
            'test.php',
            'test1.php',
            'test2.php',
            'time.php',
            'tools/.env',
            'tsconfig.app.json',
            'tsconfig.json',
            'tsconfig.spec.json',
            'uploads/.env',
            'var/log/system.log',
            'vendor/.env',
            'vendor/laravel/.env',
            'web/.env',
            'wp-admin/.env',
            'wp-config.php',
            'wp-config.php.bak',
            'wp-config.php.old',
            'wp-content/.env',
            'wp-login.php',
            'www/.env',
            'x.php',
            'xmlrpc.php',
            'xo.php',
            'xx.php',
        ];
        return in_array($path, $paths);
    }
}

